displayName=Pricewatch
author=Oveduumnakal
description=Watchlist of Grand Exchange prices with charts, market ratings and alerts
tags=price,prices,live price,ge,grand exchange,market,wiki,chart,graph,volume,volatility,liquidity,buy limit,alch,alchemy,watchlist,watch,alert,notification,flip,flipping,overlay
plugins=com.oveduumnakal.pricewatch.PricewatchPlugin
version=0.1
build=standard
